# Generated by Django 6.1.1 on 2026-09-12 05:42

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0004_enrollment_lessonprogress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_offers', to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='OPEN', max_length=16)),
                ('subtotal_amount_minor', models.PositiveBigIntegerField()),
                ('discount_amount_minor', models.PositiveBigIntegerField(default=0)),
                ('total_amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('course_title_snapshot', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_orders', to='learning.course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_orders', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commerce.courseoffer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='courseoffer',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='commerce_offer_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='courseoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('course', 'currency'), name='unique_active_offer_per_course_currency'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'FULFILLED', 'CANCELLED', 'EXPIRED'])), name='commerce_order_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount_minor__lte', models.F('subtotal_amount_minor'))), name='commerce_order_discount_lte_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount_minor', django.db.models.expressions.CombinedExpression(models.F('subtotal_amount_minor'), '-', models.F('discount_amount_minor')))), name='commerce_order_total_consistent'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount_minor__gt', 0)), name='commerce_order_total_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('learner', 'course'), name='unique_open_order_per_learner_course'),
        ),
    ]
