# Generated by Django 6.1.1 on 2026-09-12 05:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='CREATED', max_length=16)),
                ('operation_key', models.UUIDField(unique=True)),
                ('merchant_reference', models.CharField(max_length=128, unique=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commerce.order')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['CREATED', 'PENDING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'EXPIRED'])), name='commerce_payment_valid_status'), models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='commerce_payment_amount_gt_zero'), models.UniqueConstraint(condition=models.Q(('provider_transaction_id__isnull', False)), fields=('provider', 'provider_transaction_id'), name='unique_payment_provider_transaction'), models.UniqueConstraint(condition=models.Q(('status__in', ['CREATED', 'PENDING'])), fields=('order',), name='unique_payable_payment_per_order')],
            },
        ),
    ]
