# Generated by Django 6.1.1 on 2026-09-12 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('merchant_reference', models.CharField(max_length=128)),
                ('provider_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(max_length=128)),
                ('provider_status', models.CharField(max_length=128)),
                ('amount_minor', models.PositiveBigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('payload_digest', models.CharField(max_length=128)),
                ('authenticity_verified_at', models.DateTimeField()),
                ('authenticity_method', models.CharField(max_length=128)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='commerce.payment')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('processing_status__in', ['RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED'])), name='commerce_event_valid_processing_status'), models.UniqueConstraint(condition=models.Q(('provider_event_id__isnull', False)), fields=('provider', 'provider_event_id'), name='unique_provider_event_identity')],
            },
        ),
    ]
