# Generated by Django 6.1.1 on 2026-09-12 06:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_providerevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('REFUND', 'Refund'), ('REVERSAL', 'Reversal'), ('CHARGEBACK', 'Chargeback')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('operation_key', models.UUIDField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('initiation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_financial_adjustments', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_adjustments', to='commerce.payment')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['REFUND', 'REVERSAL', 'CHARGEBACK'])), name='commerce_adjustment_valid_kind'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'FAILED'])), name='commerce_adjustment_valid_status'), models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='commerce_adjustment_amount_gt_zero'), models.UniqueConstraint(condition=models.Q(('operation_key__isnull', False)), fields=('operation_key',), name='unique_adjustment_operation_key'), models.UniqueConstraint(condition=models.Q(('provider_reference__isnull', False)), fields=('payment', 'provider_reference'), name='unique_adjustment_provider_reference')],
            },
        ),
    ]
