# Generated by Django 6.1.1 on 2026-09-12 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_financialadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntegrityCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_key', models.CharField(max_length=255, unique=True)),
                ('reason', models.CharField(choices=[('AMOUNT_MISMATCH', 'Amount mismatch'), ('CURRENCY_MISMATCH', 'Currency mismatch'), ('PROVIDER_IDENTITY_MISMATCH', 'Provider identity mismatch'), ('LATE_PAYMENT_CLOSED_ORDER', 'Late payment against closed order'), ('MULTIPLE_SUCCESSFUL_PAYMENTS', 'Multiple successful payments'), ('PARTIAL_CHARGEBACK', 'Partial chargeback'), ('FULFILLMENT_INCONSISTENCY', 'Fulfillment inconsistency')], max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=16)),
                ('resolution', models.CharField(blank=True, choices=[('FULFILL', 'Fulfill'), ('REFUND', 'Refund'), ('KEEP_ACCESS', 'Keep access'), ('REVOKE_PURCHASE_ACCESS', 'Revoke purchase access'), ('NO_ACTION', 'No action')], max_length=32, null=True)),
                ('resolution_reason', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_integrity_cases', to='commerce.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integrity_cases', to='commerce.payment')),
                ('provider_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integrity_cases', to='commerce.providerevent')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_payment_integrity_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('reason__in', ['AMOUNT_MISMATCH', 'CURRENCY_MISMATCH', 'PROVIDER_IDENTITY_MISMATCH', 'LATE_PAYMENT_CLOSED_ORDER', 'MULTIPLE_SUCCESSFUL_PAYMENTS', 'PARTIAL_CHARGEBACK', 'FULFILLMENT_INCONSISTENCY'])), name='commerce_integrity_case_valid_reason'), models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'RESOLVED'])), name='commerce_integrity_case_valid_status'), models.CheckConstraint(condition=models.Q(('order__isnull', False), ('payment__isnull', False), ('provider_event__isnull', False), _connector='OR'), name='commerce_integrity_case_has_reference'), models.CheckConstraint(condition=models.Q(('resolution__isnull', True), ('resolution__in', ['FULFILL', 'REFUND', 'KEEP_ACCESS', 'REVOKE_PURCHASE_ACCESS', 'NO_ACTION']), _connector='OR'), name='commerce_integrity_case_valid_resolution')],
            },
        ),
    ]
