# Generated by Django 6.1.1 on 2026-09-12 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_paymentintegritycase'),
        ('learning', '0004_enrollment_lessonprogress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SCHOLARSHIP', 'Scholarship'), ('ADMIN_GRANT', 'Admin grant')], max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=16)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('grant_reason', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='learning.course')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='granted_course_entitlements', to=settings.AUTH_USER_MODEL)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_entitlements', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_entitlements', to='commerce.order')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_course_entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('source__in', ['PURCHASE', 'SCHOLARSHIP', 'ADMIN_GRANT'])), name='commerce_entitlement_valid_source'), models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'REVOKED'])), name='commerce_entitlement_valid_status'), models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('source', 'PURCHASE')), models.Q(('order__isnull', True), ('source__in', ['SCHOLARSHIP', 'ADMIN_GRANT'])), _connector='OR'), name='commerce_entitlement_source_order_consistent'), models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order',), name='unique_entitlement_per_order'), models.UniqueConstraint(condition=models.Q(('source', 'PURCHASE'), ('status', 'ACTIVE')), fields=('learner', 'course'), name='unique_active_purchase_entitlement')],
            },
        ),
    ]
