# Generated by Django 6.1.1 on 2026-09-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_courseentitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerevent',
            name='adjustment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerevent',
            name='adjustment_cumulative_amount_minor',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerevent',
            name='adjustment_kind',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='providerevent',
            name='is_partial_adjustment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerevent',
            name='observed_payment_status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='providerevent',
            name='provider_adjustment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
