# Generated by Django 6.1.1 on 2026-09-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_providerevent_adjustment_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
