# Generated by Django 6.1.1 on 2026-09-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserelease',
            name='audience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courserelease',
            name='level',
            field=models.CharField(default='Foundation', max_length=80),
        ),
        migrations.AddField(
            model_name='courserelease',
            name='outcomes',
            field=models.TextField(blank=True, help_text='One learning outcome per line.'),
        ),
        migrations.AddField(
            model_name='courserelease',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
